[mgr]
show_hidden = true
sort_by = "alphabetical"
sort_dir_first = true
show-symlink = true

[opener]
play = [
  { run = 'vlc "$@"', orphan = true, for = "linux" },
]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "linux" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]
view = [
  { run = 'timg "$@"', orphan = true, for = "linux" },
]

[open]
rules = [
  { mime = "text/*", use = "edit" },
  { mime = "video/*", use = "play" },
  { mime = "image/*", use = "view" },
  { mime = "audio/*", use = "play" },
  { name = "*.html", use = [ "open", "edit" ] },
  { name = "*.json", use = "edit" },
  { name = "*.py", use = "edit" }, 
  { name = "*.sh", use = "edit" },
  { name = "*.toml", use = "edit" },
  { name = "*.y*ml", use = "edit" },
  { name = "*config", use = "edit" },
  { name = "*.cfg", use = "edit" },
  { name = "*env", use = "edit" },
  { name = "*.d", use = "edit" },
  { name = "*.md", use = "edit" },
  { name = "*.txt", use = "edit" },
  { name = ".zsh*", use = "edit" },
  { name = "*.ini", use = "edit" },
  { name = "*.lua", use = "edit" },
  { name = "*.xml", use = "edit" },
  { name = "*.log", use = "edit" },
# open with normal / gnome / kde
  { name = "*.ods", use = "open" },
  { name = "*.pdf", use = "open" },
# open with multimedia player
  { name = "*.mp3", use = "play" },

]
append_rules = [
	{ name = "*", use = "edit" },
]

[input]
cursor_blink = true
